site_name: 我的全新博客
site_url: https://你的用户名.github.io/blog/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs  # 👈 就是加了这一行来开启顶部导航
plugins:
  - blog

nav:
  - 首页: index.md
  - 专栏博客: blog/index.md